name: superlinter

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Latest Super-Linter
        uses: github/super-linter@v4.6.2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run julia-actions/julia-processcoverage@v1
        uses: julia-actions/julia-processcoverage@v1
      
      - name: Run codecov/codecov-action@v1
        uses: codecov/codecov-action@v1
